# Site settings
title: Selz on GitHub
description: > # this means to ignore newlines until "baseurl:"
  Open Source & Plugins 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://selz.com/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
highlighter: rouge
